name: Daily scheduled script execution
on:
  schedule:
    - cron: '0 5 * * *' # 5 AM UTC / 7 AM Hamburg
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-python: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run script
        env:
          SUPA_URL: ${{ secrets.SUPA_URL }}
          HAM_API_KEY: ${{ secrets.HAM_API_KEY }}
        run: python main.py
